### ISSUE TITLE
Type error in EditablePage component?

### ISSUE THREAD

**Issue by moarief** [redabacha/magnolia-frontend-helpers#17]
Hi,

We are currently using the standard package from Magnolia and wanted to try this package to minimize bundle size.

After adding the package and updating import we get this error: Types of property 'componentMappings' are incompatible.

Property 'componentMappings' is missing in type '{ "......-lm:pages/home-page": ComponentType<any>; "......-lm:pages/home-category": (props: any) => JSX.Element; "......-lm:pages/article": (props: any) => EmotionJSX.Element | ""; ... 24 more ...; ".....-lm:components/pageBanner": FC<...>; }' but required in type '{ componentMappings: { [key: string]: ComponentType<any>; }; }'.ts(2741)

Would be nice to get an introduction to differences between standard package and you package.

**Comment by redabacha** [comment]
hi @MoActive,

this package is pretty much a rewrite at this point of the original `@magnolia/react-editor` package, you can see a list of basic differences in the README. there's not much documentation other than that due to lack of time atm (and majority of it would be identical to [upstream](https://docs.magnolia-cms.com/product-docs/6.2/Developing/SPA-development-and-Magnolia/Magnolia-front-end-helpers-for-SPA/Magnolia-React-Editor.html) anyway). however the source code is quite a lot smaller than upstream so feel free to poke around and contribute if you'd like. it's used in production at https://www.hollandandbarrett.com/ for reference.

and as you can tell all the components have typings for them now. it looks like you might be passing the `config` object incorrectly to `EditablePage`? the component mappings need to be set under `componentMappings` in the `config` object, so it'd look something like: `const config = { componentMappings: { ... } };` and `<EditablePage config={config} />`.

**Comment by moarief** [comment]
Hi @redabacha,

Thanks for getting back.

Will take another look at the componentMappings. I did build our own DynamicModules function to handle component rendering on pages, but data from Magnolia is not consistent at this time, so will give it another go later.
